# Generated by Django 4.0 on 2023-01-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'orden', 'verbose_name_plural': 'ordenes'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'producto ordenado', 'verbose_name_plural': 'productos ordenados'},
        ),
    ]
